<a href="https://colab.research.google.com/github/vipinkumarcp/NLP_Practice/blob/main/FakenewsclassifierusingLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd

In [27]:
fake_news = pd.read_csv('/content/Fake.csv')

In [28]:
true_news = pd.read_csv('/content/True.csv')

In [29]:
fake_news.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"


In [30]:
true_news.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"


In [31]:
fake_news['label'] = 1

In [32]:
fake_news

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",1
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",1
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",1
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",1


In [33]:
true_news['label'] = 0

In [34]:
df = pd.concat([true_news,fake_news],ignore_index=True)

df = df.sample(frac=1).reset_index(drop=True)

In [35]:
df.isnull().sum()

,0
title,0
text,0
subject,0
date,0
label,0


In [36]:
X = df.drop('label',axis=1)

In [37]:
y = df['label']

In [38]:
X.shape

(44898, 4)

In [39]:
y.shape

(44898,)

In [40]:
import tensorflow as tf

In [41]:
tf.__version__

'2.19.0'

In [42]:
from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [43]:
#vocabulary size
voc_size = 5000


In [44]:
#one hot respresentation
messages = X.copy()

In [45]:
messages['title'][1]

'Suspected U.S. drone strike targets militants in Pakistan, regional official says'

In [46]:
messages

,title,text,subject,date
0,TOMI LAHREN: “AFTER 8 YEARS…We were part of a ...,,politics,"Jan 26, 2017"
1,Suspected U.S. drone strike targets militants ...,"PARACHINAR/PESHAWAR, Pakistan (Reuters) - A su...",worldnews,"September 15, 2017"
2,U.S. ally seen clinching re-election in Hondur...,TEGUCIGALPA (Reuters) - Eight years after a co...,worldnews,"November 23, 2017"
3,"U.S. looks to Facebook, private groups to batt...","WASHINGTON (Reuters) - The U.S. government, ac...",politicsNews,"February 25, 2016"
4,Senate votes to confirm Gottlieb as head of FDA,(Reuters) - The U.S. Senate voted on Tuesday t...,politicsNews,"May 9, 2017"
...,...,...,...,...
44893,Iraq steps up retaliation against Kurdish inde...,BAGHDAD (Reuters) - Iraq stopped selling dolla...,worldnews,"October 3, 2017"
44894,Investors buoyed by Trump's readiness to move ...,(Reuters) - Wall Street’s predilection for a g...,politicsNews,"March 24, 2017"
44895,Nine killed as burqa-clad Taliban attack Pakis...,"PESHAWAR, Pakistan (Reuters) - Pakistani Talib...",worldnews,"December 1, 2017"
44896,Canada's Trudeau warns against 'tempting short...,"PROVIDENCE, R.I. (Reuters) - Canadian Prime Mi...",politicsNews,"July 14, 2017"


In [47]:
#messages.reset_index(inplace=True)

In [48]:
messages

,title,text,subject,date
0,TOMI LAHREN: “AFTER 8 YEARS…We were part of a ...,,politics,"Jan 26, 2017"
1,Suspected U.S. drone strike targets militants ...,"PARACHINAR/PESHAWAR, Pakistan (Reuters) - A su...",worldnews,"September 15, 2017"
2,U.S. ally seen clinching re-election in Hondur...,TEGUCIGALPA (Reuters) - Eight years after a co...,worldnews,"November 23, 2017"
3,"U.S. looks to Facebook, private groups to batt...","WASHINGTON (Reuters) - The U.S. government, ac...",politicsNews,"February 25, 2016"
4,Senate votes to confirm Gottlieb as head of FDA,(Reuters) - The U.S. Senate voted on Tuesday t...,politicsNews,"May 9, 2017"
...,...,...,...,...
44893,Iraq steps up retaliation against Kurdish inde...,BAGHDAD (Reuters) - Iraq stopped selling dolla...,worldnews,"October 3, 2017"
44894,Investors buoyed by Trump's readiness to move ...,(Reuters) - Wall Street’s predilection for a g...,politicsNews,"March 24, 2017"
44895,Nine killed as burqa-clad Taliban attack Pakis...,"PESHAWAR, Pakistan (Reuters) - Pakistani Talib...",worldnews,"December 1, 2017"
44896,Canada's Trudeau warns against 'tempting short...,"PROVIDENCE, R.I. (Reuters) - Canadian Prime Mi...",politicsNews,"July 14, 2017"


In [49]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [50]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [51]:
corpus

['tomi lahren year part differ march march vote booth vote trump video',
 'suspect u drone strike target milit pakistan region offici say',
 'u alli seen clinch elect hondura vote eight year coup',
 'u look facebook privat group battl onlin extrem',
 'senat vote confirm gottlieb head fda',
 'boom sarah huckabe sander set media straight differ trump volunt meet clinton dnc pay million fake russian dossier',
 'u n mediat de mistura attend syria talk friday report',
 'jill stein demand recount hillari camp use desper effort stop trump hillari clinton will risk civil war america video',
 'drain obama radic swamp rep chaffetz call obama appoint fed gov ethic director uneth public critic trump',
 'wow confirm ice time deport illeg alien protect sanctuari counti suspect arsonist behind worst fire ca histori',
 'republican disarray deepen trump attack rebel conserv',
 'woman want elect bulli whose campaign work shadi oper incit violenc women children senior citizen video',
 'canada g presid fo

In [52]:
corpus[1]

'suspect u drone strike target milit pakistan region offici say'

In [53]:
onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

[[4338, 1809, 1189, 251, 3132, 2831, 2831, 4784, 16, 4784, 1612, 847],
 [3048, 4692, 1740, 1690, 4290, 1662, 535, 1194, 1674, 165],
 [4692, 2863, 3732, 2943, 3976, 2906, 4784, 2867, 1189, 3922],
 [4692, 2420, 85, 1432, 4370, 4260, 3582, 1595],
 [116, 4784, 785, 1294, 76, 4447],
 [1254,
  4266,
  1960,
  3510,
  1239,
  900,
  1089,
  3132,
  1612,
  2599,
  4794,
  2823,
  1889,
  3255,
  208,
  4614,
  156,
  1449],
 [4692, 1059, 3142, 3398, 4495, 474, 1496, 1914, 446, 4825],
 [2297,
  4837,
  1232,
  1451,
  4435,
  2091,
  1692,
  3657,
  1385,
  3207,
  1612,
  4435,
  2823,
  2848,
  3304,
  2405,
  3193,
  1132,
  847],
 [346,
  2727,
  547,
  3637,
  4250,
  1001,
  3311,
  2727,
  4441,
  1560,
  2383,
  3685,
  957,
  991,
  2938,
  2649,
  1612],
 [3239,
  785,
  323,
  1202,
  4027,
  3824,
  2913,
  3016,
  4323,
  2148,
  3048,
  3397,
  813,
  989,
  3067,
  1561,
  4963],
 [1236, 336, 635, 1612, 1190, 2701, 313],
 [2603,
  767,
  3976,
  417,
  4811,
  3195,
  1414,
  29

In [54]:
corpus[1]

'suspect u drone strike target milit pakistan region offici say'

In [55]:
onehot_repr[1]

[3048, 4692, 1740, 1690, 4290, 1662, 535, 1194, 1674, 165]

In [56]:
#Embedding represnation

In [57]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4784 1612  847]
 [   0    0    0 ... 1194 1674  165]
 [   0    0    0 ... 2867 1189 3922]
 ...
 [   0    0    0 ... 1190 3825 2777]
 [   0    0    0 ... 1996 1878 4598]
 [   0    0    0 ... 1622 4101 4341]]


In [58]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3048,
       4692, 1740, 1690, 4290, 1662,  535, 1194, 1674,  165], dtype=int32)

In [59]:

## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size,embedding_vector_features))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [61]:
len(embedded_docs),y.shape

(44898, (44898,))

In [62]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [66]:
X_final.shape

(44898, 20)

In [67]:
y_final.shape

(44898,)

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33)

In [69]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.9057 - loss: 0.2281 - val_accuracy: 0.9308 - val_loss: 0.1757
Epoch 2/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9531 - loss: 0.1219 - val_accuracy: 0.9389 - val_loss: 0.1520
Epoch 3/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.9658 - loss: 0.0905 - val_accuracy: 0.9370 - val_loss: 0.1794
Epoch 4/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9741 - loss: 0.0709 - val_accuracy: 0.9394 - val_loss: 0.1841
Epoch 5/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9800 - loss: 0.0542 - val_accuracy: 0.9377 - val_loss: 0.2040
Epoch 6/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9846 - loss: 0.0420 - val_accuracy: 0.9347 - val_loss: 0.2447
Epoch 7/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9888 - loss: 0.0308 - val_accuracy: 0.9350 - val_loss: 0.2442
Epoch 8/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9891 - loss: 0.0290 - val_accuracy: 0.

In [70]:
y_pred=model.predict(X_test)

464/464 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step


In [71]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [72]:
from sklearn.metrics import confusion_matrix

In [73]:
confusion_matrix(y_test,y_pred)

array([[6583,  544],
       [ 437, 7253]])

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.933792265640818

In [75]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93      7127
           1       0.93      0.94      0.94      7690

    accuracy                           0.93     14817
   macro avg       0.93      0.93      0.93     14817
weighted avg       0.93      0.93      0.93     14817

