<a href="https://colab.research.google.com/github/vipinkumarcp/NLP_Practice/blob/main/Wordtovec_and_bow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import pandas as pd

In [91]:
messages =  pd.read_csv('/content/SMSSpamCollection',sep='\t',names=['lablel','message'])

In [92]:
messages

,lablel,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [93]:
messages.shape

(5572, 2)

In [94]:
messages['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."

In [95]:
#data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [96]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [97]:
#stemming and stopwords
corpus = []
for i in range(0,len(messages)):
  # print(messages['message'][i])
  review = re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
  review = review.lower()
  review = review.split()
  # print(review)

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  # print(review)
  review = ' '.join(review)
  # print(review)
  corpus.append(review)





In [98]:
len(corpus)

5572

In [99]:
#creating the bag of the words

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500, binary=True,ngram_range=(2,2))
#It creates a binary bag-of-words representation with a limited vocabulary of the most frequent 2500 terms.
X = cv.fit_transform(corpus).toarray()

In [100]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [101]:
y = pd.get_dummies(messages['lablel'])

In [102]:
y

,ham,spam
0,True,False
1,True,False
2,False,True
3,True,False
4,True,False
...,...,...
5567,False,True
5568,True,False
5569,True,False
5570,True,False


In [103]:
y = y.iloc[:,1].values

In [104]:
#Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)


In [105]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)
#

In [106]:
#prediction
y_pred = spam_detect_model.predict(X_test)

In [107]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9713004484304932
              precision    recall  f1-score   support

       False       0.97      1.00      0.98       955
        True       1.00      0.80      0.89       160

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.94      1115
weighted avg       0.97      0.97      0.97      1115



In [108]:
#creating TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features=2500)
X = cv.fit_transform(corpus).toarray()
#

In [109]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [110]:
y_pred = spam_detect_model.predict(X_test)

In [111]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))


0.9847533632286996
              precision    recall  f1-score   support

       False       0.98      1.00      0.99       955
        True       1.00      0.89      0.94       160

    accuracy                           0.98      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.98      0.98      1115



In [112]:
#wordtovec

In [113]:
!pip install gensim
#gensim have pretrained and also we can train the model from the scratch

In [114]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [115]:
vec_king = wv['king']

In [116]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [117]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [118]:
#stemming and stopwords
corpus = []
for i in range(0,len(messages)):
  # print(messages['message'][i])
  review = re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
  review = review.lower()
  review = review.split()
  # print(review)

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  # print(review)
  review = ' '.join(review)
  # print(review)
  corpus.append(review)


In [119]:
from nltk import sent_tokenize


In [120]:
from gensim.utils import simple_preprocess

In [121]:
corpus[0]

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [122]:
nltk.download('punkt_tab')
#simple process concerst a list of document into lowercase token
words = []
for sent in corpus:
  sent_token = sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [123]:
words


[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'appli',
  'over'],
 ['dun', 'say', 'earli', 'hor', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though'],
 ['freemsg',
  'hey',
  'darl',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chg',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['winner',
  'valu',
  'network',
  'custom',
  'select',
  'receivea',
  'prize',
  'r

In [124]:
import gensim

In [125]:
#This trains a Word2Vec model that learns word meanings using a context window of 5 and ignores rare words appearing less than twice.
model = gensim.models.Word2Vec(words,min_count=2,window=5)

In [126]:
#It returns the vocabulary (list of learned words) from the Word2Vec model, ordered by frequency.
model.wv.index_to_key

['call',
 'go',
 'get',
 'ur',
 'gt',
 'lt',
 'come',
 'day',
 'ok',
 'free',
 'know',
 'love',
 'like',
 'time',
 'good',
 'want',
 'got',
 'text',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'take',
 'stop',
 'see',
 'home',
 'think',
 'repli',
 'lor',
 'sorri',
 'still',
 'tell',
 'mobil',
 'back',
 'da',
 'dont',
 'make',
 'phone',
 'pleas',
 'week',
 'hi',
 'say',
 'new',
 'work',
 'later',
 'pl',
 'hope',
 'miss',
 'ask',
 'co',
 'msg',
 'min',
 'meet',
 'dear',
 'night',
 'messag',
 'happi',
 'wait',
 'well',
 'give',
 'thing',
 'tri',
 'much',
 'great',
 'oh',
 'claim',
 'wat',
 'hey',
 'number',
 'friend',
 'thank',
 'way',
 'ye',
 'www',
 'let',
 'prize',
 'feel',
 'right',
 'even',
 'tomorrow',
 'win',
 'pick',
 'alreadi',
 'care',
 'said',
 'cash',
 'im',
 'amp',
 'leav',
 'yeah',
 'tone',
 'realli',
 'babe',
 'find',
 'life',
 'morn',
 'sleep',
 'last',
 'keep',
 'servic',
 'year',
 'uk',
 'nokia',
 'sure',
 'com',
 'would',
 'buy',
 'anyth',
 'use',
 'contact',
 'start',

In [127]:
model.corpus_count

5565

In [128]:
model.wv.similar_by_word('claim')

[('award', 0.9994741678237915),
 ('call', 0.9994145035743713),
 ('cash', 0.9993594288825989),
 ('prize', 0.9993182420730591),
 ('mobil', 0.9992076754570007),
 ('line', 0.999197781085968),
 ('number', 0.9991769790649414),
 ('free', 0.9991141557693481),
 ('land', 0.9991036653518677),
 ('pleas', 0.9990922212600708)]

In [129]:
model.wv['kid'].shape

(100,)

In [139]:
import numpy as np
#This function converts a document into a single vector by averaging the Word2Vec embeddings of its words.

def avg_word2vec(doc):
    vectors = [model.wv[word] for word in doc if word in model.wv.key_to_index]

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

In [131]:
!pip install tqdm

In [140]:
from tqdm import tqdm

In [141]:
words[70]

['wah', 'lucki', 'man', 'save', 'money', 'hee']

In [134]:
type(model.wv.index_to_key)

list

In [142]:
X = []
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))


100%|██████████| 5565/5565 [00:00<00:00, 5750.74it/s]


In [136]:
type(X)

list

In [143]:
X_new = np.array(X)

In [144]:
X_new

array([[-0.16478182,  0.19227453,  0.04753439, ..., -0.17472167,
         0.07086299,  0.01620953],
       [-0.12831983,  0.1425377 ,  0.03277833, ..., -0.12280244,
         0.05431309,  0.01284618],
       [-0.15562078,  0.18469958,  0.04447957, ..., -0.1677243 ,
         0.0734539 ,  0.01846037],
       ...,
       [-0.03758832,  0.03881387,  0.00888993, ..., -0.03848367,
         0.02248196,  0.0078107 ],
       [-0.19111969,  0.21792173,  0.05552272, ..., -0.19794343,
         0.08566872,  0.02132079],
       [-0.12948669,  0.1438521 ,  0.03472173, ..., -0.13511048,
         0.05727084,  0.01567315]])

In [145]:
X_new[0].shape

(100,)

In [146]:
words[0]

['go',
 'jurong',
 'point',
 'crazi',
 'avail',
 'bugi',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amor',
 'wat']

In [147]:
X_new[0]

array([-0.16478182,  0.19227453,  0.04753439, -0.03156028,  0.07126959,
       -0.41231927,  0.13785858,  0.5454945 , -0.08451745, -0.14228249,
       -0.18532932, -0.33846292, -0.06100662,  0.04747202,  0.05629427,
       -0.20891541,  0.03371902, -0.34054103, -0.00474502, -0.47928366,
        0.09643838,  0.18166173,  0.10673239, -0.16113403, -0.07666782,
       -0.00066607, -0.23307256, -0.24428891, -0.21410698,  0.12151417,
        0.22069953,  0.04966409,  0.04876265, -0.19318028, -0.12865464,
        0.35319683, -0.04499839, -0.19988036, -0.1716461 , -0.44470087,
        0.02551602, -0.18412012, -0.05283576,  0.0328652 ,  0.24954289,
       -0.10985485, -0.18875712, -0.16236898,  0.17694847,  0.23839219,
        0.12070217, -0.28518978, -0.09518144,  0.00951265, -0.20965463,
        0.19346863,  0.12043247,  0.02231775, -0.24054246,  0.05722311,
        0.10254013,  0.10712395, -0.06918103, -0.07158563, -0.36183164,
        0.13902079,  0.08653989,  0.18911368, -0.2139854 ,  0.23

In [148]:
#Text → Tokenized words → Word2Vec → Average → X_new