<a href="https://colab.research.google.com/github/vipinkumarcp/NLP_Practice/blob/main/word_Embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)


2.19.0


In [3]:
from  tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
### Vocabulary size
voc_size=500

In [6]:
#one hot encoding
#It loops through each word in sent and converts it into a numeric index using one_hot, creating a list of those indices.
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[494, 28, 230, 440], [494, 28, 230, 374], [494, 407, 230, 277], [292, 477, 235, 34, 42], [292, 477, 235, 34, 41], [349, 494, 153, 230, 468], [447, 427, 390, 34]]


In [21]:
#word embedding represntation

from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential



In [22]:
import numpy as np


In [11]:
#to make all snetnce one hotting same size ..sentance leghn we can max legth of biggest sentence...pre padding zero in front
sent_length = 8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 494  28 230 440]
 [  0   0   0   0 494  28 230 374]
 [  0   0   0   0 494 407 230 277]
 [  0   0   0 292 477 235  34  42]
 [  0   0   0 292 477 235  34  41]
 [  0   0   0 349 494 153 230 468]
 [  0   0   0   0 447 427 390  34]]


In [12]:
#now we need convert each and every value to convert vectors ...
#here i'm taking my feature representenation dimensions to 10
dim = 10

In [31]:
#embedding layer similar to word to vec
model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [24]:
model.summary

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.predict(np.array([embedded_docs[1]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[[ 4.0278744e-02, -3.3663072e-02,  2.5751833e-02, -1.5870072e-02,
         -3.3940911e-02, -2.9450942e-02,  4.7123346e-02,  2.0302895e-02,
          1.9516710e-02,  4.2866055e-02],
        [ 4.0278744e-02, -3.3663072e-02,  2.5751833e-02, -1.5870072e-02,
         -3.3940911e-02, -2.9450942e-02,  4.7123346e-02,  2.0302895e-02,
          1.9516710e-02,  4.2866055e-02],
        [ 4.0278744e-02, -3.3663072e-02,  2.5751833e-02, -1.5870072e-02,
         -3.3940911e-02, -2.9450942e-02,  4.7123346e-02,  2.0302895e-02,
          1.9516710e-02,  4.2866055e-02],
        [ 4.0278744e-02, -3.3663072e-02,  2.5751833e-02, -1.5870072e-02,
         -3.3940911e-02, -2.9450942e-02,  4.7123346e-02,  2.0302895e-02,
          1.9516710e-02,  4.2866055e-02],
        [-2.5301291e-02,  1.4656100e-02, -4.2952120e-02, -3.5285950e-05,
          3.2257292e-02, -1.7874517e-02,  1.2383834e-03, -3.4730531e-02,
         -9.8769665e-03,  4.3950390e-02],
        [-4.8972931e-02, -3.0194962e-02, -2.4172246e-02,  3.

In [35]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


array([[[ 4.0278744e-02, -3.3663072e-02,  2.5751833e-02, -1.5870072e-02,
         -3.3940911e-02, -2.9450942e-02,  4.7123346e-02,  2.0302895e-02,
          1.9516710e-02,  4.2866055e-02],
        [ 4.0278744e-02, -3.3663072e-02,  2.5751833e-02, -1.5870072e-02,
         -3.3940911e-02, -2.9450942e-02,  4.7123346e-02,  2.0302895e-02,
          1.9516710e-02,  4.2866055e-02],
        [ 4.0278744e-02, -3.3663072e-02,  2.5751833e-02, -1.5870072e-02,
         -3.3940911e-02, -2.9450942e-02,  4.7123346e-02,  2.0302895e-02,
          1.9516710e-02,  4.2866055e-02],
        [ 4.0278744e-02, -3.3663072e-02,  2.5751833e-02, -1.5870072e-02,
         -3.3940911e-02, -2.9450942e-02,  4.7123346e-02,  2.0302895e-02,
          1.9516710e-02,  4.2866055e-02],
        [-2.5301291e-02,  1.4656100e-02, -4.2952120e-02, -3.5285950e-05,
          3.2257292e-02, -1.7874517e-02,  1.2383834e-03, -3.4730531e-02,
         -9.8769665e-03,  4.3950390e-02],
        [-4.8972931e-02, -3.0194962e-02, -2.4172246e-02,  3.